server:
  port: 80
  servlet:
    encoding:
      charset: utf-8

spring:
  application:
    name: sso-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xc19981004
    url: jdbc:mysql://8.142.142.224:3306/yxj
  redis:
    #数据库索引
    database: ${REDIS_DB:0}
    #host: ${REDIS_HOST:8.142.142.224}
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:}
    #连接超时时间
    timeout: 15000
  mail:
    host: smtp.qq.com
    username: 1907930264@qq.com
    password: bfdezdovgoekbgfa
    port: 25

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #???????package?????????
  typeAliasesPackage: com.yxj.ssoserver.mappers.entity
  global-config:
    # ???????
    db-config:
      #????  AUTO:"???ID??", INPUT:"????ID",ID_WORKER:"????ID (??????ID)", UUID:"????ID UUID";
      #id-type: id_worker
      #???? IGNORED:"????",NOT_NULL:"? NULL ??"),NOT_EMPTY:"????"
      #field-strategy: not_empty
      #???????
      column-underline: true
      #??????????
      #capital-mode: true
      #??????
      #db-type: h2
    #??mapper ????
    refresh: true
  # ????
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000